name: linux
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: CI-Build
        run: |
          chmod +x ci-build.sh
          ./ci-build.sh
          cp ~/go/bin/tealsp ../tealsp
      - name: Prepare version file
        run: echo $GITHUB_SHA > version
      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          tag: dev
          artifacts: "tealsp"
          prerelease: true